---
name: java

releases:
- name: java
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: java_job
  azs: [z1]
  instances: 1
  jobs:
  - name: java
    release: java
    properties: {}
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
